dist: trusty
sudo: false

# Want 'bash' but 'c' works:
language: c

branches:
  only:
  - master
  - /^release\//

script:
- GIT_COMMITTER_NAME=Bob
  GIT_COMMITTER_EMAIL=bob@blob.net
  GIT_AUTHOR_NAME='Bob Blob'
  GIT_AUTHOR_EMAIL=bob@blob.net
  PROVEOPT=-v make test
