dist: trusty
sudo: false

# Want 'bash' but 'c' works:
language: c

script:
- git checkout ${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH}
- GIT_COMMITTER_NAME=Bob
  GIT_COMMITTER_EMAIL=bob@blob.net
  GIT_AUTHOR_NAME='Bob Blob'
  GIT_AUTHOR_EMAIL=bob@blob.net
  PROVEOPT=-v make test
